version: "1.0"
services:
  api:    
    build:      
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mssql     
    ports:
      - "8080:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BingeBot123!"
    restart: unless-stopped    
    ports:
      - "1433:1433"